name: Frontend CI

on:
  push:
    branches: [main, develop, 'test/*']
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    # - name: Run linter
    #   run: npm run lint

    - name: Build project
      run: npm run build

    - name: Check build output
      run: |
        echo "Build completed successfully!"
        echo "Build size:"
        du -sh dist/
        echo "Files in dist:"
        find dist -type f -name "*.js" -o -name "*.css" -o -name "*.html" | head -10 